spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 68468122-8955-45ee-a5b7-3d87972325b1
  datasource:
    url: jdbc:mysql://34.81.32.251:3306/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Lzc123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: nacos-provide-order
server:
  port: 8040
seata:
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace: 68468122-8955-45ee-a5b7-3d87972325b1
      username: nacos
      password: nacos
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace: 68468122-8955-45ee-a5b7-3d87972325b1
      username: nacos
      password: nacos
  # 配置服务分组
  tx-service-group: default_tx_group
  service:
    vgroupMapping:
      default_tx_group: default
  enable-auto-data-source-proxy: false
nacos:
  config:
    server-addr: 127.0.0.1:8848
    namespace: 68468122-8955-45ee-a5b7-3d87972325b1