spring:
  cloud:
    alibaba:
      seata:
        # 配置服务分组
        tx-service-group: default_tx_group
    nacos:
      discovery:
        server-addr: ${NACOS_HOST}:${NACOST_PORT}
        namespace: ${NACOS_NAMESPACE}
  datasource:
    url: jdbc:mysql://${MYSQL_IP}:${MYSQL_PORT}/seata_order?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: nacos-provide-order
server:
  port: 8040
seata:
  config:
    type: nacos
    nacos:
      server-addr: ${NACOS_HOST}:${NACOST_PORT}
      group: SEATA_GROUP
      namespace: ${NACOS_NAMESPACE}
      username: ${NACOS_USERNAME}
      password: ${NACOS_PASSWORD}
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: ${NACOS_HOST}:${NACOST_PORT}
      group: SEATA_GROUP
      namespace: ${NACOS_NAMESPACE}
      username: ${NACOS_USERNAME}
      password: ${NACOS_PASSWORD}
  enable-auto-data-source-proxy: false
nacos:
  config:
    server-addr: ${NACOS_HOST}:${NACOST_PORT}
    namespace: ${NACOS_NAMESPACE}