spring:
  cloud:
    nacos:
      discovery:
        server-addr: 34.81.32.251:8848
        namespace: 68468122-8955-45ee-a5b7-3d87972325b1
  datasource:
    url: jdbc:mysql://34.81.32.251:3306/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Lzc123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: nacos-provide-stock
server:
  port: 8041
