spring:
  cloud:
    nacos:
      discovery:
        server-addr: 34.81.32.251:8848
        namespace: 96c38075-ceee-4a22-b69d-d0d14b8a2449
  datasource:
    url: jdbc:mysql://34.81.32.251:3306/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Lzc123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: nacos-provide-stock
server:
  port: 8041
